#include "NebulaLogging.h"	

DEFINE_LOG_CATEGORY(LogDataAsset);
DEFINE_LOG_CATEGORY(LogGameplay);
DEFINE_LOG_CATEGORY(LogBackend);
DEFINE_LOG_CATEGORY(LogSystemEffects);
DEFINE_LOG_CATEGORY(LogDialogue);
DEFINE_LOG_CATEGORY(LogDebug);
DEFINE_LOG_CATEGORY(LogCargo);